// Print route — renders the static character snapshot in a printer-
// friendly layout, omits companion-mode live state, and the regular
// sheet exposes a Print link in the action bar.

import { test, expect } from "@playwright/test";
import { seedCharacter } from "./helpers/seed";
import { mysticAtL1, freshL1Hero } from "./helpers/fixtures";
import { gotoSheet } from "./helpers/visit";

test.describe("Printable sheet", () => {
  // The print route auto-fires window.print() on mount. Block the dialog
  // for every test so it doesn't dangle in the headless browser.
  test.beforeEach(async ({ context }) => {
    await context.addInitScript(() => {
      window.print = () => {};
    });
  });

  test("renders the character's name and key sections", async ({ page }) => {
    const id = await seedCharacter(page, mysticAtL1);
    await page.goto(`/characters/${id}/print`);

    await expect(
      page.getByRole("heading", { level: 1, name: /Mystic L1/ }),
    ).toBeVisible();
    await expect(page.getByRole("heading", { name: /^Combat$/ })).toBeVisible();
    await expect(page.getByRole("heading", { name: /^Abilities$/ })).toBeVisible();
    await expect(page.getByRole("heading", { name: /^Skills$/ })).toBeVisible();
    await expect(page.getByRole("heading", { name: /^Spells$/ })).toBeVisible();
    // Magic Missile is in the seeded mystic's spellsKnown.
    await expect(page.getByText(/^Magic Missile$/).first()).toBeVisible();
  });

  test("does NOT render companion-mode live state", async ({ page }) => {
    const id = await seedCharacter(page, mysticAtL1);
    await page.goto(`/characters/${id}/print`);

    // No interactive companion panels.
    await expect(page.getByTestId("hp-readout")).toHaveCount(0);
    await expect(page.getByTestId("hd-readout")).toHaveCount(0);
    await expect(page.getByTestId("rest-long")).toHaveCount(0);
    await expect(page.getByTestId("slot-pip-1-0")).toHaveCount(0);
    // No Death Saves or Rest sections.
    await expect(page.getByRole("heading", { name: /Death Saves/i })).toHaveCount(0);
    await expect(page.getByRole("heading", { name: /^Rest$/i })).toHaveCount(0);
  });

  test("regular sheet exposes a Print link that opens the print route in a new tab", async ({
    page,
  }) => {
    const id = await seedCharacter(page, freshL1Hero);
    await gotoSheet(page, id);

    const link = page.getByRole("link", { name: /^Print$/ });
    await expect(link).toBeVisible();
    await expect(link).toHaveAttribute("href", `/characters/${id}/print`);
    await expect(link).toHaveAttribute("target", "_blank");
  });

  test("a character with no boons/burdens/feats hides those sections but always shows Notes", async ({
    page,
  }) => {
    const id = await seedCharacter(page, freshL1Hero);
    await page.goto(`/characters/${id}/print`);

    await expect(page.getByRole("heading", { name: /^Boons$/ })).toHaveCount(0);
    await expect(page.getByRole("heading", { name: /^Burdens$/ })).toHaveCount(0);
    // freshL1Hero has fighting-style:defense in feats array, so Feats appears.
    // (We assert Notes specifically.)
    await expect(page.getByRole("heading", { name: /^Notes$/ })).toBeVisible();
  });

  test("footer shows symbarator version and today's date", async ({ page }) => {
    const id = await seedCharacter(page, freshL1Hero);
    await page.goto(`/characters/${id}/print`);

    // Footer matches the regex `Generated by symbarator vX.Y.Z on YYYY-MM-DD`.
    await expect(
      page.getByText(/Generated by symbarator v\d+\.\d+\.\d+ on \d{4}-\d{2}-\d{2}/),
    ).toBeVisible();
  });
});
